#!/usr/bin/env bash

mkdir ssl

openssl genrsa -des3 -out ./ssl/server.key 1024
openssl req -new -key ./ssl/server.key  -out ./ssl/server.csr
cp ./ssl/server.key ./ssl/server.key.orig
openssl rsa -in ./ssl/server.key.orig -out ./ssl/server.key
openssl x509 -req -days 365 -in ./ssl/server.csr -signkey ./ssl/server.key -out ./ssl/server.crt
